language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-24

before_script:
    - chmod +x gradlew

script:
    - ./gradlew clean assemble
